#!/bin/sh
gst-launch fakesrc sizetype=2 sizemax=10 filltype=5 num-buffers=10 datarate=10  ! tee name=t t. ! mpf-identity ! mux. t. ! mpf-identity ! mux. mpf-mux name=mux debug=1 ! fakesink dump=true

