#!/bin/bash

if [ $# != 1 ]
then
read -p "Enter filename to convert to flv: " FILENAME
else
FILENAME=$1
fi

echo "Converting $FILENAME to $FILENAME.flv"
gst-launch filesrc location=$FILENAME ! decodebin name=dec ffmux_flv name=mux \
 ! filesink location=$FILENAME.flv dec. ! queue ! ffmpegcolorspace \
 ! videoscale ! video/x-raw-yuv,width=320 ! ffenc_flv ! queue \
 ! mux. dec.audio_01 ! queue ! audioconvert ! lame ! mp3parse ! queue ! mux.

