#!/bin/sh

# Inputs: (apply to launch line like this: gstargs=-v ./test-1)
#
#   prefix:	  Prefix to apply to launch line (e.g. "gdb --args" for debugging)
#   args:     Arguments to supply to prefix (e.g. prefix=valgrind args=-v)
#   version:  Use specific version of gstlaunch (e.g. prefix=valgrind version=-0.10)
#   gstargs:  Gstreamer arguments (e.g. gst-args=-v)
#

export GST_PLUGIN_PATH=../.libs:$GST_PLUGIN_PATH

# Drive a fake source into a multi-pipe identity.
#
$prefix $args gst-launch$version $gstargs \
    fakesrc num-buffers=100  sizetype=2 sizemax=10 filltype=4 datarate=100 do-timestamp=true ! \
	mpf-pipeline loglevel=0 one-pipeline=true pipeline="appsrc ! identity dump=true ! appsink"  ! fakesink async=false sync=false
