#!/bin/sh

# Perform motion detection on a video, and show the internal object detection in one video window.
# When regions of interest are detected, show them in a second window, and capture them to a file.

alpha=${alpha:=0.03}
median=${median:=19}
video=${video:=$MPF_HOME/media/freedom-day.1.mpg}
draw_all=${draw_all:=false}
visualization=${visualization:=final}
picture_threshold=${picture_threshold:=30}
momentum_threshold=${momentum_threshold:=5000}
width=${width:=320}
height=${height:=240}
fps=${fps:=0}
concurrent=${concurrent:=1}
shift=${shift:=2}
sustain=${sustain:=90}

mkdir sc
basename=sc/`basename $video`

fakesink="fakesink async=false sync=false"
rdfsink="mpf-rdf-ton3 ! filesink location=$basename-%1\$d.n3 sync=false async=false"

$prefix $args gst-launch$version $gstargs filesrc location=$video ! decodebin ! tee name=t ! queue ! \
    ffmpegcolorspace ! toiplimage ! queue ! mpf-opencv-md name=md draw-all=$draw_all alpha=$alpha median=$median visualization=$visualization picture-threshold=$picture_threshold momentum-threshold=$momentum_threshold \
    md.output ! tee name=t1 \
    t1. ! queue ! fromiplimage ! videoscale ! video/x-raw-rgb, width=$width, height=$height ! ffmpegcolorspace ! videoscale ! ximagesink sync=false async=false max-lateness=-1 \
    md.interest ! queue ! mpf-loi-smooth threshold=1 sustain=$sustain ! mpf-shift shift=$shift ! tee name=ti \
    mpf-segmenter name=seg threshold=1 fps=$fps mpf-debug=0 loglevel=2 \
    ti. ! queue ! seg.metadata \
    t. ! queue ! seg.input \
    seg.output ! ffmpegcolorspace ! videoscale ! video/x-raw-rgb, width=$width, height=$height ! ximagesink async=false sync=false max-lateness=-1 \
