#!/bin/sh

sleep=${sleep:=0.02}
video=${video:=$MPF_HOME/media/freedom-day.1.mpg}

basename=`basename $video`
mkdir sc

$prefix $args gst-launch$version $gstargs filesrc location=$video ! decodebin ! \
    mpf-identity sleep=$sleep dump=none ! ffmpegcolorspace ! \
    toiplimage ! iplidentity ! fromiplimage ! \
    videoscale ! ffmpegcolorspace ! ffenc_mpeg4 ! ffmux_mp4 ! filesink location=sc/$basename.2.1.mp4 \

