#!/bin/sh

# Perform motion detection on a video, and show the internal object detection in one video window.
# When regions of interest are detected, show them in a second window, and capture them to a file.

alpha=${alpha:=0.03}
median=${median:=19}
video=${video:=$MPF_HOME/media/freedom-day.1.mpg}
draw_all=${draw_all:=false}
visualization=${visualization:=final}
picture_threshold=${picture_threshold:=30}
momentum_threshold=${momentum_threshold:=5000}
width=${width:=320}
height=${height:=240}
fps=${fps:=0}
concurrent=${concurrent:=1}
shift=${shift:=2}
sustain=${sustain:=90}

usc=${usc:=usc}

fakesink="fakesink async=false sync=false"
ximagesink="ximagesink async=true sync=false max-lateness=-1"

rdfsink="mpf-rdf-ton3 ! filesink location=$basename-%1\$d.n3 sync=false async=false"

$prefix $args gst-launch$version $gstargs filesrc location=$video ! decodebin ! \
    mpf-window count=1200 repeat=1201 ! mpf-pipeline loglevel=0 concurrent=$concurrent name="pipe" pipeline="appsrc ! ffmpegcolorspace ! videoscale ! video/x-raw-rgb, width=320, height=240 ! $ximagesink" ! $fakesink

