#!/bin/sh

sleep=${sleep:=0}
video=${video:=$MPF_HOME/media/freedom-day.1.mpg}
draw_all=${draw_all:=false}
visualization=${visualization:=final}
daytime=${daytime:=true}
sync=${sync:=false}

basename=`basename $video`

if [ $daytime == true ]; then
    echo "Day-Time"
    alpha=${alpha:=0.03}
    picture_threshold=${picture_threshold:=25}
    motion_threshold=${motion_threshold:=3000}
    median=${median:=11}
else
    echo "Night-Time"
    alpha=${alpha:=0.01}
    picture_threshold=${picture_threshold:=20}
    motion_threshold=${motion_threshold:=1000}
    median=${median:=9}
fi

width=${width:=320}
height=${height:=240}

. $PWD/credentials

$prefix $args gst-launch$version $gstargs \
    filesrc location=$video ! \
    decodebin ! videobalance contrast=1 brightness=0 ! mpf-identity sleep=$sleep dump=none ! ffmpegcolorspace ! \
    toiplimage ! mpf-opencv-md name=md draw-all=$draw_all alpha=$alpha visualization=$visualization picture-threshold=$picture_threshold momentum-threshold=$motion_threshold median=$median \
    md.output ! queue ! fromiplimage ! ffmpegcolorspace ! ximagesink async=false sync=$sync \
    md.interest ! queue ! mpf-loi-smooth loglevel=1 preset=5 sustain=15 threshold=1 ! mpf-loi-seg threshold=1 ! \
    mpf-rdf-ton3 ! filesink location=$basename.seg.n3 sync=$sync async=false \

