#!/bin/sh


# Verifies handling of EOS.

filesink="filesink location=/dev/stdout async=false sync=false"

$prefix $args gst-launch$version $gstargs fakesrc sizetype=2 sizemax=1 filltype=5 num-buffers=60 datarate=10 ! \
    mpf-toi start=2 interval=1 duration=0.5 verbose=1 ! mpf-loi-seg loglevel=0 ! mpf-test-eos name=eos \
    eos.output ! $filesink \
    eos.events ! queue ! $filesink \
