#!/bin/sh
#
# Split a stream, window it, and process it in parallel.  Read and decode a real file. TODO: This does not
# parallel process yet, the decoder apparently controls playback rate of the pipeline.  See test-9 for
# equivalent behavior using fakesrc.
#
video=${video:=$MPF_HOME/media/freedom-day.1.mpg}

$prefix $args gst-launch$version filesrc location=$video ! decodebin ! tee name=t \
  t. ! queue ! mpf-window count=20 repeat=40 ! mpf-identity sleep=0.01 ! fakesink sync=false async=false \
  t. ! queue ! mpf-window start=50 count=20 repeat=40 ! mpf-identity sleep=0.01 ! fakesink sync=false async=false
