#!/bin/sh -x
#
# Remove then re-instate buffer times. Note that the preserve=false is counteracted by using mpf-identity
# restamp (15 frame per second).
#
debug=0

width=${width:=320}
height=${height:=240}
restamp=${restamp:=15}
video=${video:=$MPF_HOME/media/freedom-day.1.mpg}

$prefix $args gst-launch$version \
    filesrc location=$video ! decodebin ! mpf-window preserve=false ! \
    videoscale ! video/x-raw-yuv, width=$width, height=$height ! \
    mpf-identity dump=buffers restamp=$restamp ! ffmpegcolorspace ! ximagesink max-lateness=-1 async=false

