#!/bin/sh
#
# Overlapping buffers, datarate non-zero.
#
mpfdebug=1

$1 $prefix $args gst-launch$version fakesrc num-buffers=40 sizemax=16 filltype=4 sizetype=2 datarate=10 ! tee name=t \
  t. ! queue ! mpf-window name=window-0 start=0 count=10 repeat=15 mpf-debug=$mpfdebug loglevel=1 ! fakesink dump=true sync=false async=false  \
  t. ! queue ! mpf-window name=window-1 start=8 count=10 repeat=15 mpf-debug=$mpfdebug loglevel=1 ! fakesink dump=true sync=false async=false