#!/bin/sh
# Note: the queue is essential to avoid deadlock here.  Send outputs to fakesinks, threading
# in queues will cause interleave of output from dumps.
#
$prefix $args gst-launch$version fakesrc num-buffers=5 ! mpf-test-eos name=test \
  test.output ! queue ! fakesink dump=true \
  test.events ! queue ! fakesink dump=true
